pcData <- read.delim("household_power_consumption.txt", header = TRUE, sep = ";")
pcData <- pcData[ which(pcData$Date == "1/2/2007" | pcData$Date == "2/2/2007"), ]
pcData$Date <- strptime(paste(pcData$Date,pcData$Time), "%d/%m/%Y %H:%M:%S")
par(mfcol=c(1,1), mar=c(3.6, 3, 3, 1.5))
plot(pcData$Date,as.numeric(as.character(pcData$Sub_metering_1)), type = "l", ylab="Energy sub metering", xlab = "", cex.main=0.75, cex.lab=0.75, cex.axis=0.75, mgp = c (2, .5, 0 ), tck=-.02)
lines(pcData$Date,as.numeric(as.character(pcData$Sub_metering_2)),col="red")
lines(pcData$Date,as.numeric(as.character(pcData$Sub_metering_3)),col="blue")
legend('topright', c("Sub_metering_1","Sub_metering_2","Sub_metering_3") , lwd=1, col=c('black', 'red', 'blue'),cex=.70)
dev.copy(png,'plot3.png', width = 480, height = 480, units = "px")
dev.off()